### ISSUE TITLE
Spelling Consistency

### ISSUE THREAD

**Issue by BrianLambert118** [The-Lab-at-OPM/HCD-Guides#13]
USAJobs or USA Jobs. Need to be consistent throughout the document.

**Comment by anatecture** [comment]
thanks for this note; Sarah Hughes, our editor, also saw this issue. I have a note to our Comms team to see if we have editorial guidance on it. will resolve as soon as possible. in the meantime, could you link to a couple of places where you saw it?

**Comment by anatecture** [comment]
okay just got word back @BrianLambert118, and apparently it's called USAJOBS, which seems very shout-y but ¯\_(ツ)_/¯ I guess that's what we go with. Link me to a couple places where you've seen it and I'll start enforcing consistency

**Comment by BrianLambert118** [comment]
Here is what i found.

Products; Products-Service Spectrum; Digital Product: 
•	Government examples include the digital filing system from the US Patent Office, the **USAJobs** website, and the Library of Congress' digital archives.

Systems:
•	The website **USAJobs.gov** is a product that creates access to the hiring system.

Systems; Case Study: Systems in Government; **USAJOBS** Mission Critical Hiring Paths Diagram
•	Teams rebuilding the outdated **USAJobs** site studied the interactions of **USAJobs.gov** product and the system of hiring closely.
•	Even though each of these groups is working towards the same goal, the successful functioning of the **USAJobs** site, the definition of success differs slightly across each group.
•	In this way, the effort to improve the **USAJobs** site became an effort to improve hiring itself, thusly demonstrating the utility of finding and working from the root cause of an issue, instead of solving for discreet, surface issues.
•	In building this diagram, the **USA Jobs** team created an illustration of the hiring path components: people, stages, and touchpoints.
•	This understanding then informed the development of the **USAJobs** site product in terms of the various stakeholders' positions and needs in the system.
